### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by vbxerxes** [URV-cheminformatics/DecoyFinder#3]
Hello,

I can't find the windows installer anywhere and don't have acess to any other OS where i can run the software. The installation file is missing? If not, can someone give instructions on how to run the program in a Windows 10 machine?

Thanks in advance

**Comment by ssorgatem** [comment]
I just uploaded all the windows executables I had lying around for the latest build here: https://github.com/URVquimioinformatica-COS/DecoyFinder/releases/tag/v2.0

**Comment by vbxerxes** [comment]
Thank you very much!
