### ISSUE TITLE
No available installer in the repository

### ISSUE THREAD

**Issue by LicoriceLin** [URV-cheminformatics/DecoyFinder#5]
Hi,
the project's mainpage is 404-missing, while the repository here didn't provide an out-of-the-box installer. I failed to compile it from the nsi file. could you please upload the installer somewhere?

**Comment by ssorgatem** [comment]
You can find them in the "Releases" section.
Here's a link: https://github.com/URVquimioinformatica-COS/DecoyFinder/releases
